getlago/lago-docs

- docs/api/04_events.mdx
According to the Event arguments sequence, there is mismatch in the docs:
https://github.com/getlago/lago-nodejs-client/blob/c588635f9323a12f012aa6ba76d884fe418225b4/lib/models/event.js#L2
> Node.js Events code example, fix arguments sequence

- docs/guide/02_self-hosting/docker.md
Following https://github.com/getlago/lago/issues/47 issue, a change has been introduced in [lago-front](https://github.com/getlago/lago-front/pull/236) to add a new environment variable to disable the Sign-up page
This change adds the documentation of `LAGO_DISABLE_SIGNUP` environment variable
Related to https://github.com/getlago/lago/pull/73
> update: Document LAGO_DISABLE_SIGNUP env variable

- config.json
Root URL of the Lago documentation has been updated from https://doc.getlago.com/docs/guide/intro to https://doc.getlago.com/docs/guide/intro/welcome in [this commit](https://github.com/getlago/lago-docs/commit/e7e99d7762b0e0d4548ccec3e78bee0d522e35da).
The goal of this PR is to update links to the Lago official documentation on this repo.
> fix: Update lago documentation url

- docs/api/06_events/create-batch-event.mdx
- docs/api/06_events/create-event.mdx
- docs/guide/04_billable-metrics/aggregation-types.md
The objective of this feature is to introduce a system of persistent billable metrics that do not resume to 0 at the end of a billing period.
Document the event and batch event changes to add or remove a recurring persisted object.
> feat(persisted-metrics): Document event properties

- docs/api/02_billable_metrics/destroy-billable-metric.mdx
- docs/api/03_plans/destroy-plan.mdx
- docs/api/07_coupons/destroy-coupon.mdx
Error handling in services and the way it's rendered in API needs a complete refactoring.
The objective of this pull request is to document all the `405 Method Not Allowed` HTTP errors returned in the API end points
Related to https://github.com/getlago/lago-api/pull/444
> feat(error): Document not allowed error

- docs/api/05_subscriptions/subscription-object.mdx
We want to add the `previous_plan_code` and `next_plan_code` to the subscription object.
> feat: Add previous and next plan code to subscription object

- docs/api/05_subscriptions/subscription-object.mdx
We want to add the `previous_external_id` and `next_external_id` to the subscription object.
> feat: Add previous and next external id to subscription object

- docs/api/05_subscriptions/subscription-object.mdx
When a downgrade is made, `external_id` is copied from the original to the new subscription.
Instead of returning `external_id`, we want to return the downgrade plan date of the subscription in the API.
> misc: Add downgrade plan date instead of next and previous external id

- docs/api/05_subscriptions/create-subscription.mdx
- docs/api/07_coupons/apply-coupon.mdx
- docs/api/08_add_ons/apply-add-on.mdx
- docs/api/11_webhooks/messages.mdx
This PR documents error status for former `missing_argument` errors (previously returned as 422) that were turned into proper `404` errors:
This impacts:
- Apply a coupon route
- Apply an add on route
- Create a subscription route
- Event error webhook
https://github.com/getlago/lago-api/pull/462
> feat(errors): Document former missing arguments errors

- docs/api/09_invoices/update-invoice-status.mdx
This PR documents the validation error of the `PUT /api/v1/invoices/:id` route
https://github.com/getlago/lago-api/pull/477
> feat(errors): Document error handling on invoice status update

- docs/api/03_plans/create-plan.mdx
- docs/api/03_plans/plan-object.mdx
- docs/api/03_plans/update-plan.mdx
In order to be consistent between all charge models, we want to store `properties` by using the same type.
The goal of this MR is to:
- update `properties` from `array` to `hash` for graduated charges
- rename `ranges` to `volume_ranges` for the volume properties key
> misc: Use graduated ranges and volume ranges as hash

- docs/api/02_billable_metrics/create-billable-metric.mdx
- docs/api/02_billable_metrics/update-billable-metric.mdx
👉  https://github.com/getlago/lago/issues/32
We want to be able to price differently billable metrics according to several dimensions (groups).
For example, creating a `storage` pricing based on the `region of the server` and the `cloud provider` used.
This PR adds `group` on `billable_metric` creation.
⚠️ The update on billable metric object will be done on a next PR.
> feat(groups): Add group on billable metric creation

- docs/api/04_customers/create-update-customer.mdx
- docs/api/04_customers/customer-object.mdx
- docs/api/10_organizations/organization-object.mdx
- docs/api/10_organizations/update-organization.mdx
👉  https://github.com/getlago/lago/issues/99
The goal of this PR is to move fields related to Billing or Invoice into `billing_configuration`.
For customer: `vat_rate`.
For organization: `invoice_footer`, `vat_rate`.
> misc: Move fields related to Billing or Invoice into billing_configuration

- docs/api/13_wallets/create-wallet.mdx
Hi Guys
Ran into this issue when creating a wallet against a new customer account.   The create wallet documentation excludes the currency argument which is defined as not null in the wallet object description.
**See error returned by lago-api in console :**
[c523ac3e-9351-4eae-b5a5-504c1511be3a] ActiveRecord::NotNullViolation (PG::NotNullViolation: ERROR:  null value in column "currency" of relation "wallets" violates not-null constraint
lago-api      | DETAIL:  Failing row contains (9c7f2c2e-e9ad-460a-a7d8-fa52ddab9b02, 4346a882-d999-450f-a60d-6528e59d68ce, 0, null, test, 1.00000, 0.00000, 0.00000, 0.00000, null, null, null,
Currency is a required argument when creating a wallet.   If currency is not included a http 500 is returned.
> FIX: Create wallet documentation missing currency argument - create-wallet.mdx

- docs/api/04_customers/create-update-customer.mdx
I noticed all other tributes had code segments with \`, jut on sync it was missing, so I added it since this is easier than just explaining on slack where exactly I found the missing ones.
> added missing code highlighting with backticks in 'sync' attribute

- docs/api/02_billable_metrics/billable-metric-object.mdx
- docs/api/02_billable_metrics/destroy-billable-metric.mdx
👉  https://github.com/getlago/lago/issues/179
As a user, I want to be able to delete a billable metric that is linked to a subscription in case of a change of pricing (e.g. we no longer charge customers based on the number of API calls).
Once deleted, the corresponding charges will be removed from the plans and from all draft invoices.
Deleted metrics will still be included in past invoices (i.e. finalized invoices).
The goal of this PR is to add on the billable metric response:
- `active_subscriptions_count`
- `draft_invoices_count`
It also removes the 405 response from the delete query
These fields are used to know the impact of deleting billable metric.
> feat(delete_bm): Update response for billable metric deletion

- docs/api/07_customer_usage/customer-usage.mdx
- docs/guide/10_invoicing/fees.md
Back-end improved and implemented a better rounding calculation system across the app.
Updating the doc to explain how the rounding calculation is done inside Lago system
> doc(fee): Add fee rounding rules

- docs/api/04_customers/create-update-customer.mdx
- docs/api/04_customers/customer-object.mdx
@mathieu-lago Since we share the same endpoint for both create and update probably we will have to separate it somehow due to this change. For `update`, metadata object can have `id` attribute but for `create` there is no `id` parameter... Any idea?
> feat (customer metadata): Add API docs for customer metadata

- changelog/document-locale.md
- changelog/timezones.md
- config.json
- docs/guide/06_customers/invoice_customer.md
- docs/guide/98_testing-integration.md
After releasing the documentation for Customers metadata, the deploy failed because of some broken links
Fix the broken links in the documentation
> doc(Customers): Fix all broken links

- docs/api/99_resources/locales.mdx
Lago is supporting the locale Norwegian (Bokmål), we should update our documentation.
Update of docs/api/ressources/locales and add Norwegian (Bokmål) in the list of locales supported by Lago.
> doc(Ressources): Add nb as locale in doc

- docs/api/02_billable_metrics/billable-metric-object.mdx
- docs/api/03_plans/plan-object.mdx
Plans edition has some issue if you update some properties of a billable metric, especially if you change groups definition or aggregation type :
"After the billable metric edition, new dimensions are created with new group_id that do not match the ones in the plans already defined"
This PR exposes a new `plans_count` field in the `BillableMetric` response type to let the API users know if the BM is editable.
Related to https://github.com/getlago/lago-api/pull/914
> feat(bm): Expose count of attached plans

- docs/api/90_webhooks/message-signature.mdx
Javascript client code snippet to retrieve the webhook public key was not explicit enough
The client  response needs to be manipulated in order to be checked
This PR udpated the documentation to make the process explicit
> bug(webhook): fix javascript public key snippet

- docs/api/14_wallets/wallet-object.mdx
In our data model, amounts are usually integers in cents (e.g. `amount_cents` or `vat_amount_cents`).
However, in wallet, amount attributes are defined in float and exposed as string in the two API
This difference makes it difficult for users to use this information for calculation purposes (e.g. cannot easily deduct `amount_cents` from `balance` without converting the attribute into an integer).
This PR changes turned wallet fields into bigint and adds currency columns to match the amount and currency handling from other models.
- `balance_cents` / `balance_currency`
For compatibility purpose, all float fields are still exposed in public API but are deprecated.
This changes also requires an update of the front-end to adapt to the new amount fields
Related PR on API: …
> feat: Turn balance float amounts into cents

- docs/api/06_events/estimate-instant.mdx
- docs/api/11_fees/fee-object.mdx
- docs/api/11_fees/get-all-fees.mdx
- docs/api/11_fees/update-fee.mdx
👉  https://getlago.canny.io/feature-requests/p/instantly-charge-the-customer-when-an-event-is-processed
Fintech companies want to deduct fees as transactions occur. They need to charge their customers instantly and report those fees in the invoice issued at the end of the billing period.
Example: 0.5% charge on FX transfers. When the customer makes a transfer of $100, they are immediately charged $0.5 (automatically deducted from their wallet). The corresponding fee is included in the invoice sent to the customer at the end of the billing period.
This PR adds the documentation for the new `POST api/v1/events/estimate_fees` route
Related to https://github.com/getlago/lago-api/pull/923
> feat(instant_charge): Document API route to estimate instant fees amount

- docs/api/07_customer_usage/customer-usage-object.mdx
This anchor ref: https://doc.getlago.com/docs/api/customer_usage/customer-usage-object#charge:~:text=Related%20charge%20object is dead because of a typo. This PR fixes it.
😜
> fix charge-object anchor ref

- docs/api/09_coupons/apply-coupon.mdx
Updates the doc to mention the new exposed attribute of the `applied_coupon` object: `coupon_name`
> feat(applied_coupon): coupon name is present in object
